@startuml packages_CustomUnitaj
set namespaceSeparator none
package "unitraj" as unitraj {
}
package "unitraj.configs" as unitraj.configs {
}
package "unitraj.configs.experiment_config" as unitraj.configs.experiment_config {
}
package "unitraj.configs.path_config" as unitraj.configs.path_config {
}
package "unitraj.configs.wandb_config" as unitraj.configs.wandb_config {
}
package "unitraj.data_analysis" as unitraj.data_analysis {
}
package "unitraj.datasets" as unitraj.datasets {
}
package "unitraj.datasets.MTR_dataset" as unitraj.datasets.MTR_dataset {
}
package "unitraj.datasets.autobot_dataset" as unitraj.datasets.autobot_dataset {
}
package "unitraj.datasets.base_dataparser" as unitraj.datasets.base_dataparser {
}
package "unitraj.datasets.base_dataset" as unitraj.datasets.base_dataset {
}
package "unitraj.datasets.common_utils" as unitraj.datasets.common_utils {
}
package "unitraj.datasets.dataparser" as unitraj.datasets.dataparser {
}
package "unitraj.datasets.types" as unitraj.datasets.types {
}
package "unitraj.datasets.wayformer_dataset" as unitraj.datasets.wayformer_dataset {
}
package "unitraj.evaluation" as unitraj.evaluation {
}
package "unitraj.k_means" as unitraj.k_means {
}
package "unitraj.lightning" as unitraj.lightning {
}
package "unitraj.lightning.lit_datamodule" as unitraj.lightning.lit_datamodule {
}
package "unitraj.lightning.lit_module" as unitraj.lightning.lit_module {
}
package "unitraj.lightning.lit_trainer_factory" as unitraj.lightning.lit_trainer_factory {
}
package "unitraj.models" as unitraj.models {
}
package "unitraj.models.autobot" as unitraj.models.autobot {
}
package "unitraj.models.autobot.autobot" as unitraj.models.autobot.autobot {
}
package "unitraj.models.base_model" as unitraj.models.base_model {
}
package "unitraj.models.base_model.av2_eval" as unitraj.models.base_model.av2_eval {
}
package "unitraj.models.base_model.base_model" as unitraj.models.base_model.base_model {
}
package "unitraj.models.base_model.model_utils" as unitraj.models.base_model.model_utils {
}
package "unitraj.models.base_model.waymo_eval" as unitraj.models.base_model.waymo_eval {
}
package "unitraj.models.mtr" as unitraj.models.mtr {
}
package "unitraj.models.mtr.MTR" as unitraj.models.mtr.MTR {
}
package "unitraj.models.mtr.MTR_utils" as unitraj.models.mtr.MTR_utils {
}
package "unitraj.models.mtr.loss_utils" as unitraj.models.mtr.loss_utils {
}
package "unitraj.models.mtr.motion_utils" as unitraj.models.mtr.motion_utils {
}
package "unitraj.models.mtr.ops" as unitraj.models.mtr.ops {
}
package "unitraj.models.mtr.ops.attention" as unitraj.models.mtr.ops.attention {
}
package "unitraj.models.mtr.ops.attention.attention_utils" as unitraj.models.mtr.ops.attention.attention_utils {
}
package "unitraj.models.mtr.ops.attention.attention_utils_v2" as unitraj.models.mtr.ops.attention.attention_utils_v2 {
}
package "unitraj.models.mtr.ops.knn" as unitraj.models.mtr.ops.knn {
}
package "unitraj.models.mtr.ops.knn.knn_utils" as unitraj.models.mtr.ops.knn.knn_utils {
}
package "unitraj.models.mtr.transformer" as unitraj.models.mtr.transformer {
}
package "unitraj.models.mtr.transformer.multi_head_attention" as unitraj.models.mtr.transformer.multi_head_attention {
}
package "unitraj.models.mtr.transformer.multi_head_attention_local" as unitraj.models.mtr.transformer.multi_head_attention_local {
}
package "unitraj.models.mtr.transformer.position_encoding_utils" as unitraj.models.mtr.transformer.position_encoding_utils {
}
package "unitraj.models.mtr.transformer.transformer_decoder_layer" as unitraj.models.mtr.transformer.transformer_decoder_layer {
}
package "unitraj.models.mtr.transformer.transformer_encoder_layer" as unitraj.models.mtr.transformer.transformer_encoder_layer {
}
package "unitraj.models.wayformer" as unitraj.models.wayformer {
}
package "unitraj.models.wayformer.wayformer" as unitraj.models.wayformer.wayformer {
}
package "unitraj.models.wayformer.wayformer_utils" as unitraj.models.wayformer.wayformer_utils {
}
package "unitraj.utils" as unitraj.utils {
}
package "unitraj.utils.base_config" as unitraj.utils.base_config {
}
package "unitraj.utils.config" as unitraj.utils.config {
}
package "unitraj.utils.console" as unitraj.utils.console {
}
package "unitraj.utils.tsne" as unitraj.utils.tsne {
}
package "unitraj.utils.utils" as unitraj.utils.utils {
}
package "unitraj.utils.visualization" as unitraj.utils.visualization {
}
package "unitraj.viz" as unitraj.viz {
}
unitraj --> unitraj.configs.experiment_config
unitraj --> unitraj.configs.path_config
unitraj --> unitraj.configs.wandb_config
unitraj --> unitraj.datasets.base_dataset
unitraj --> unitraj.datasets.dataparser
unitraj --> unitraj.lightning.lit_datamodule
unitraj --> unitraj.lightning.lit_trainer_factory
unitraj --> unitraj.models.autobot.autobot
unitraj.configs.experiment_config --> unitraj.configs.path_config
unitraj.configs.wandb_config --> unitraj.configs.path_config
unitraj.data_analysis --> unitraj.datasets
unitraj.data_analysis --> unitraj.datasets.common_utils
unitraj.datasets.MTR_dataset --> unitraj.datasets.base_dataset
unitraj.datasets.autobot_dataset --> unitraj.datasets.base_dataset
unitraj.datasets.base_dataparser --> unitraj.datasets.common_utils
unitraj.datasets.base_dataparser --> unitraj.datasets.dataparser
unitraj.datasets.base_dataparser --> unitraj.datasets.types
unitraj.datasets.base_dataset --> unitraj.datasets.dataparser
unitraj.datasets.base_dataset --> unitraj.datasets.types
unitraj.datasets.common_utils --> unitraj.datasets.types
unitraj.datasets.dataparser --> unitraj.datasets.base_dataparser
unitraj.datasets.dataparser --> unitraj.datasets.types
unitraj.datasets.wayformer_dataset --> unitraj.datasets.base_dataset
unitraj.evaluation --> unitraj.datasets
unitraj.evaluation --> unitraj.models
unitraj.evaluation --> unitraj.utils.utils
unitraj.k_means --> unitraj.datasets
unitraj.k_means --> unitraj.utils.utils
unitraj.models --> unitraj.models.autobot.autobot
unitraj.models --> unitraj.models.mtr.MTR
unitraj.models --> unitraj.models.wayformer.wayformer
unitraj.models.autobot.autobot --> unitraj.models.base_model.base_model
unitraj.models.base_model.base_model --> unitraj.models.base_model.av2_eval
unitraj.models.base_model.base_model --> unitraj.models.base_model.waymo_eval
unitraj.models.mtr.MTR --> unitraj.models.mtr.MTR_utils
unitraj.models.mtr.MTR --> unitraj.models.mtr.ops.knn
unitraj.models.mtr.MTR --> unitraj.models.mtr.transformer
unitraj.models.mtr.ops.attention.attention_utils --> unitraj.models.mtr.ops.attention
unitraj.models.mtr.ops.attention.attention_utils_v2 --> unitraj.models.mtr.ops.attention
unitraj.models.mtr.ops.knn.knn_utils --> unitraj.models.mtr.ops.knn
unitraj.models.mtr.transformer.multi_head_attention_local --> unitraj.models.mtr.ops
unitraj.models.mtr.transformer.transformer_decoder_layer --> unitraj.models.mtr.transformer.multi_head_attention
unitraj.models.mtr.transformer.transformer_decoder_layer --> unitraj.models.mtr.transformer.multi_head_attention_local
unitraj.models.mtr.transformer.transformer_decoder_layer --> unitraj.models.mtr.transformer.transformer_encoder_layer
unitraj.models.mtr.transformer.transformer_encoder_layer --> unitraj.models.mtr.transformer.multi_head_attention
unitraj.models.mtr.transformer.transformer_encoder_layer --> unitraj.models.mtr.transformer.multi_head_attention_local
unitraj.models.wayformer.wayformer --> unitraj.models.base_model.base_model
unitraj.models.wayformer.wayformer --> unitraj.models.wayformer.wayformer_utils
unitraj.utils.base_config --> unitraj.utils.console
unitraj.viz --> unitraj.datasets
unitraj.viz --> unitraj.utils.visualization
@enduml
